language: python
python:
  - "2.7"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "3.6"

# command to install dependencies
install:
  - "pip install -qq py-linq"
  - "pip install -qq meta"
  - "pip install -qq pytest"
  - "pip install -qq pytest-cov"
  - "pip install -qq flake8"
  - "pip install coveralls --quiet"
  - "pip install ."

# command to run tests
script:
  - py.test -s --cov=py_querable --cov-report xml:/tmp/cov-py_queryable.xml --junitxml=/tmp/py_queryable.xml
#  - flake8 --version
#  - flake8 --ignore E501  py_queryable tests

after_success:
  - coveralls